### ISSUE TITLE
Angular Notifier message appear over angular $dialogs popup

### ISSUE THREAD

**Issue by ramprakash-ravi** [l-lin/angular-notifier#2]
I'm using a angular dialogs popup with a form and posting a data, on which i'm using angular 'Notifier' to display success or error message.

My problem is the message is appearing in the page but is appearing below the dialog.

Is there any posibility to make toast messages over the dialog popup ?

**Comment by l-lin** [comment]
The z-index of the message is set to 1000. Try to use a bigger z-index:

``` css
.notifier-msg {
    z-index: 9999
}
```
